// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackerStats.Infrastructure.Data;

#nullable disable

namespace TrackerStats.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406043447_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackerStats.Domain.Entities.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("TrackerStats.Domain.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveTorrents")
                        .HasColumnType("integer");

                    b.Property<string>("Buffer")
                        .HasColumnType("text");

                    b.Property<long?>("DownloadedBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("HitAndRuns")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncResult")
                        .HasColumnType("text");

                    b.Property<int?>("LeechingTorrents")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Ratio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RequiredRatio")
                        .HasColumnType("numeric");

                    b.Property<string>("SeedBonus")
                        .HasColumnType("text");

                    b.Property<int?>("SeedingTorrents")
                        .HasColumnType("integer");

                    b.Property<long?>("UploadedBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("TrackerStats.Domain.Entities.IntegrationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveTorrents")
                        .HasColumnType("integer");

                    b.Property<string>("Buffer")
                        .HasColumnType("text");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DownloadedBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("HitAndRuns")
                        .HasColumnType("integer");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LeechingTorrents")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Ratio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RequiredRatio")
                        .HasColumnType("numeric");

                    b.Property<string>("SeedBonus")
                        .HasColumnType("text");

                    b.Property<int?>("SeedingTorrents")
                        .HasColumnType("integer");

                    b.Property<long?>("UploadedBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("IntegrationSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
