// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackerStats.Infrastructure.Data;

#nullable disable

namespace TrackerStats.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TrackerStats.Domain.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActiveTorrents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Buffer")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HitAndRuns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncResult")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeechingTorrents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Ratio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RequiredRatio")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedBonus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeedingTorrents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UploadedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("TrackerStats.Domain.Entities.IntegrationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActiveTorrents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Buffer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HitAndRuns")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeechingTorrents")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ratio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RequiredRatio")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedBonus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeedingTorrents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UploadedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IntegrationSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
