name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - run: dotnet restore backend/src/TrackerStats.Api/TrackerStats.Api.csproj
      - run: dotnet build backend/src/TrackerStats.Api/TrackerStats.Api.csproj --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - run: dotnet restore backend/src/TrackerStats.Api/TrackerStats.Api.csproj
      - run: dotnet test backend/src/TrackerStats.Api/TrackerStats.Api.csproj --configuration Release --no-restore
